# Generated by Django 3.0.1 on 2020-11-09 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 13, 5, 9, 106232, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
