# Generated by Django 3.0.1 on 2020-10-31 07:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0002_auto_20201031_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 7, 9, 48, 668117, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
