# Generated by Django 3.0.1 on 2020-11-12 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0002_auto_20201109_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 14, 24, 9, 53868, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
