# Generated by Django 3.0.1 on 2020-11-12 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0003_auto_20201112_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 15, 29, 59, 648667, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
