# Generated by Django 3.0.1 on 2020-11-12 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.PaymentMethod', verbose_name='ΤΡΟΠΟΣ ΠΛΗΡΩΜΗΣ'),
        ),
    ]
