# Generated by Django 3.0.1 on 2020-10-31 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, null=True, verbose_name='Επωνυμια')),
                ('address', models.CharField(blank=True, max_length=240, null=True, verbose_name='Διευθυνση')),
                ('job_description', models.CharField(blank=True, max_length=240, null=True, verbose_name='Επαγγελμα')),
                ('loading_place', models.CharField(blank=True, default='Εδρα μας', max_length=240, null=True, verbose_name='Τοπος Φορτωσης')),
                ('destination', models.CharField(blank=True, default='Εδρα του,', max_length=240, null=True, verbose_name='Προορισμος')),
                ('afm', models.CharField(blank=True, max_length=10, null=True, verbose_name='ΑΦΜ')),
                ('doy', models.CharField(blank=True, default='Σπαρτη', max_length=240, null=True, verbose_name='ΔΟΥ')),
                ('destination_city', models.CharField(blank=True, max_length=240, null=True, verbose_name='Πολη')),
                ('transport', models.CharField(blank=True, max_length=10, null=True, verbose_name='Μεταφορικο Μεσο')),
                ('first_name', models.CharField(blank=True, max_length=200, verbose_name='Ονομα')),
                ('last_name', models.CharField(blank=True, max_length=200, verbose_name='Επιθετο')),
                ('amka', models.CharField(blank=True, max_length=20, verbose_name='Ψευδονυμο')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Σημειώσεις')),
                ('cellphone', models.CharField(blank=True, max_length=20, verbose_name='Κινητό')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο')),
                ('active', models.BooleanField(default=True, verbose_name='Ενεργός')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('paid_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
            options={
                'ordering': ['title', 'afm'],
            },
        ),
        migrations.RemoveField(
            model_name='income',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='income',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='income',
            name='logistic_value',
        ),
        migrations.RemoveField(
            model_name='income',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='income',
            name='order_cost',
        ),
        migrations.RemoveField(
            model_name='income',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='income',
            name='sum_z',
        ),
        migrations.AddField(
            model_name='income',
            name='order_type',
            field=models.CharField(choices=[('a', 'ΤΙΜΟΛΟΓΙΟ'), ('b', 'ΑΠΟΔΕΙΞΗ'), ('c', 'ΑΛΛΟ')], default='a', max_length=1, verbose_name='ΕΙΔΟΣ ΠΑΡΑΣΤΑΤΙΚΟΥ'),
        ),
        migrations.AddField(
            model_name='income',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='ΦΟΡΟΣ'),
        ),
        migrations.AddField(
            model_name='income',
            name='taxes_modifier',
            field=models.IntegerField(default=24, verbose_name='ΦΠΑ'),
        ),
        migrations.AddField(
            model_name='income',
            name='title',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Σημειωσεις'),
        ),
        migrations.AlterField(
            model_name='income',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='ΚΑΘΑΡΗ ΑΞΙΑ'),
        ),
        migrations.CreateModel(
            name='CostumerPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Πληρωμενο')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Τίτλος')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Ποσό')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='incomes.Costumer', verbose_name='Πελάτης')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.PaymentMethod', verbose_name='Επιταγη')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='income',
            name='costumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='incomes.Costumer'),
        ),
    ]
