# Generated by Django 3.0.1 on 2020-10-31 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0002_auto_20201031_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostumerPaymentFromCostumerForm',
            fields=[
                ('costumerpayment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='incomes.CostumerPayment')),
            ],
            bases=('incomes.costumerpayment',),
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='amka',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='destination_city',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='loading_place',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='transport',
        ),
    ]
