# Generated by Django 3.0.1 on 2020-11-13 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Ονομασια')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='ΑΞΙΑ')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='ΠΕΡΙΓΡΑΦΗ')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='ΑΞΙΑ')),
                ('paid_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='ΠΛΗΡΩΤΕΟ ΠΟΣΟ')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Πληρωμενο;')),
                ('date', models.DateField(verbose_name='ΗΜΕΡΟΜΗΝΙΑ')),
                ('taxes_modifier', models.CharField(choices=[('a', 0), ('b', 13), ('c', 24)], default='a', max_length=1, verbose_name='ΦΠΑ')),
                ('total_taxes', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='ΦΟΡΟΣ')),
                ('clean_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='ΚΑΘΑΡΗ ΑΞΙΑ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general_expenses.GeneralExpenseCategory', verbose_name='ΚΑΤΗΓΟΡΙΑ')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
