# Generated by Django 3.0.1 on 2020-11-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalexpensecategory',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='ΑΞΙΑ'),
            preserve_default=False,
        ),
    ]
